services:
  db:
    image: postgres:15-alpine
    container_name: atlas_postgres_db
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: atlas
    ports:
      - "5433:5432"
    volumes:
      - postgres_atlas_data:/var/lib/postgresql/data
    networks:
      - cbtech-network
  atlas-server:
    image: higorcraco/atlas-server
    container_name: atlas-server
    restart: always
    build:
      context: ./server
    depends_on:
      - db
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/atlas
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: masterkey
    ports:
      - "8090:8080"
    networks:
      - cbtech-network

  atlas-web:
    image: higorcraco/atlas-web
    container_name: atlas-web
    restart: always
    build:
      context: ./web
    ports:
      - "8000:80"
    depends_on:
      - atlas-server
    environment:
      TZ: America/Sao_Paulo
    networks:
      - cbtech-network

volumes:
  postgres_atlas_data:
    driver: local


networks:
  cbtech-network:
    driver: bridge