spring:
  datasource:
    url: jdbc:h2:mem:test-atlas;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    #    password: password
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      dll-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
